apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: fastapi
    name: fastapi
    namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      name: fastapi
    spec:
      containers:
      - name: fastapi
        image: renanikeda/fastapi:v1
        ports:
        - containerPort: 8000
